feat(basebridge): add Base Bridge plugin
rabbitholegg/questdk-plugins pull request #338
Opened 2024-04-03 20:15 UTC by rontero83

2024-04-08 22:50 UTC, mmackz commented on packages/basebridge/src/test-transactions.ts
> +    ETH_FROM_ETHEREUM_TO_BASE_TEST,
Would remove this test. Since this will always match the ABI for an ETH deposit and not consider the token address.

2024-04-08 22:52 UTC, mmackz commented on packages/basebridge/src/test-transactions.ts
> +      contractAddress: ETHEREUM_ERC20_BRIDGE_ADDRESS,
Would just use a totally different contract address here

2024-04-08 23:04 UTC, mmackz commented on packages/basebridge/src/test-transactions.ts
> +      contractAddress: ETHEREUM_ETH_BRIDGE_ADDRESS,
suggest to remove this one also as it is redundant.

2024-04-08 23:06 UTC, mmackz commented on packages/basebridge/src/test-transactions.ts
> +      contractAddress: ETHEREUM_ERC20_BRIDGE_ADDRESS,
Actually, would just remove this one also. The one above it (ETH_FROM_ETHEREUM_TO_BASE_TEST) should be sufficient.

2024-04-08 23:11 UTC, mmackz commented on packages/basebridge/src/test-transactions.ts
> +      contractAddress: '0x990D07a69f23d69618e3Bb2444fA07f499193Fe4333',
Would remove this test. Since this will always match the ABI for an ETH deposit and not consider the token address.

2024-04-08 23:56 UTC, mmackz commented on packages/basebridge/src/BaseBridge.ts
> +  if (tokenAddress === ETH) {
This will be an issue as most of the time tokenAddress will be undefined (when any token is valid)

2024-04-09 00:00 UTC, mmackz commented on packages/basebridge/src/BaseBridge.ts
> +  if (tokenAddress === ETH) {
```suggestion
const bridgeFromEthereum = async (
  params: BridgeActionParams,
): Promise<TransactionFilter> => {
  const {
    amount,
    recipient,
    destinationChainId,
    sourceChainId,
    contractAddress,
    tokenAddress,
  } = params

  if (destinationChainId !== Chains.BASE || sourceChainId !== Chains.ETHEREUM) {
    return failingFilter()
  }

  if (
    contractAddress !== undefined &&
    !ethereumContracts.includes(contractAddress)
  ) {
    return failingFilter()
  }

  return compressJson({
    chainId: Chains.ETHEREUM,
    to: { $or: [ETHEREUM_ETH_BRIDGE_ADDRESS, ETHEREUM_ERC20_BRIDGE_ADDRESS] },
    input: {
      $or: [
        { $abi: ETHEREUM_ETH_ABI, _to: recipient, _value: amount },
        {
          $abi: ETHEREUM_ERC20_ABI,
          mintRecipient: recipient,
          amount,
          burnToken: tokenAddress,
        },
      ],
    },
  })
}
```

2024-04-09 00:01 UTC, mmackz commented on packages/basebridge/src/BaseBridge.ts
> +
```suggestion
const bridgeFromBase = async (
  params: BridgeActionParams,
): Promise<TransactionFilter> => {
  const {
    amount,
    recipient,
    destinationChainId,
    sourceChainId,
    contractAddress,
    tokenAddress,
  } = params
  if (destinationChainId !== Chains.ETHEREUM || sourceChainId !== Chains.BASE) {
    return failingFilter()
  }

  if (
    contractAddress !== undefined &&
    !baseContracts.includes(contractAddress)
  ) {
    return failingFilter()
  }

  const isETH = tokenAddress === ETH

  return compressJson({
    chainId: Chains.BASE,
    to: { $or: [BASE_ETH_BRIDGE_ADDRESS, BASE_ERC20_BRIDGE_ADDRESS] },
    value: isETH ? amount : undefined,
    input: {
      $or: [
        { $abi: BASE_ETH_ABI, _target: recipient },
        {
          $abi: BASE_ERC20_ABI,
          mintRecipient: recipient,
          amount,
          burnToken: tokenAddress,
        },
      ],
    },
  })
}
```

2024-04-09 01:13 UTC, mmackz commented on packages/basebridge/src/BaseBridge.ts
> +const bridgeFromEthereum = async (
```suggestion
const bridgeFromEthereum = async (
  params: BridgeActionParams,
): Promise<TransactionFilter> => {
  const {
    amount,
    recipient,
    destinationChainId,
    sourceChainId,
    contractAddress,
    tokenAddress,
  } = params

  if (destinationChainId !== Chains.BASE || sourceChainId !== Chains.ETHEREUM) {
    return failingFilter()
  }

  if (
    contractAddress !== undefined &&
    !ethereumContracts.includes(contractAddress)
  ) {
    return failingFilter()
  }

  return compressJson({
    chainId: Chains.ETHEREUM,
    to: { $or: [ETHEREUM_ETH_BRIDGE_ADDRESS, ETHEREUM_ERC20_BRIDGE_ADDRESS] },
    input: {
      $or: [
        { $abi: ETHEREUM_ETH_ABI, _to: recipient, _value: amount },
        {
          $abi: ETHEREUM_ERC20_ABI,
          mintRecipient: recipient,
          amount,
          burnToken: tokenAddress,
        },
      ],
    },
  })
}
```

2024-04-09 01:14 UTC, mmackz commented on packages/basebridge/src/BaseBridge.ts
> +const bridgeFromBase = async (
```suggestion
const bridgeFromBase = async (
  params: BridgeActionParams,
): Promise<TransactionFilter> => {
  const {
    amount,
    recipient,
    destinationChainId,
    sourceChainId,
    contractAddress,
    tokenAddress,
  } = params
  if (destinationChainId !== Chains.ETHEREUM || sourceChainId !== Chains.BASE) {
    return failingFilter()
  }

  if (
    contractAddress !== undefined &&
    !baseContracts.includes(contractAddress)
  ) {
    return failingFilter()
  }

  const isETH = tokenAddress === ETH

  return compressJson({
    chainId: Chains.BASE,
    to: { $or: [BASE_ETH_BRIDGE_ADDRESS, BASE_ERC20_BRIDGE_ADDRESS] },
    value: isETH ? amount : undefined,
    input: {
      $or: [
        { $abi: BASE_ETH_ABI, _target: recipient },
        {
          $abi: BASE_ERC20_ABI,
          mintRecipient: recipient,
          amount,
          burnToken: tokenAddress,
        },
      ],
    },
  })
}
```

2024-04-09 01:20 UTC, mmackz commented on packages/basebridge/src/BaseBridge.test.ts
> +      test('when bridge eth from ethereum to base', async () => {
Personally I find these tests to be very cumbersome and not very beneficial. Lately I have been replacing these action filter tests for this set of generic tests. Up to you if you want to replace it with this or update the existing ones to work with the proposed changes.  
      
      
     ``` 
      test('when making a valid bridge action', async () => {
        const filter = await bridge({
          sourceChainId: 1,
          destinationChainId: 56,
        })
        expect(filter).toBeTypeOf('object')
        expect(Number(filter.chainId)).toBe(1)
        if (typeof filter.to === 'string') {
          expect(filter.to).toMatch(/^0x[a-fA-F0-9]{40}$/)
        } else {
          // if to is an object, it should have a logical operator as the only key
          expect(filter.to).toBeTypeOf('object')
          expect(Object.keys(filter.to)).toHaveLength(1)
          expect(
            ['$or', '$and'].some((prop) =>
              Object.hasOwnProperty.call(filter.to, prop),
            ),
          ).to.be.true
          expect(Object.values(filter.to)[0]).to.satisfy((arr: string[]) =>
            arr.every((val) => val.match(/^0x[a-fA-F0-9]{40}$/)),
          )
        }
        // Check the input property is the correct type and has a valid filter operator
        expect(filter.input).toBeTypeOf('object')
        expect(
          ['$abi', '$abiParams', '$abiAbstract', '$or', '$and'].some((prop) =>
            Object.hasOwnProperty.call(filter.input, prop),
          ),
        ).to.be.true
      })
      ```

2024-04-09 01:33 UTC, mmackz commented on packages/basebridge/src/BaseBridge.ts
> +const bridgeFromBase = async (
Sorry, you can ignore these. Your method seems to work just fine.

2024-04-09 01:36 UTC, mmackz commented on packages/basebridge/src/BaseBridge.ts
> +  if (tokenAddress === ETH) {
On further inspection it seems to work fine 👍

2024-04-09 01:50 UTC, mmackz requested changes

2024-04-09 01:50 UTC, mmackz commented on packages/basebridge/package.json
> +  "private": true,
Set this to false please, or remove it.

2024-04-09 08:56 UTC, rontero83 commented on packages/basebridge/package.json
> +  "private": true,
done

2024-04-09 15:37 UTC, mmackz approved these changes

2024-04-09 17:06 UTC, merged