feat(gains): add gains plugin with options task support
rabbitholegg/questdk-plugins pull request #353
Opened 2024-04-17 17:10 UTC by rontero83

2024-04-18 02:56 UTC, mmackz commented on packages/gains/src/Gains.ts
> +  if (chainId !== Chains.ARBITRUM_ONE) {
We want to retain the ability to add new chain in the future. If the chainId is not correct, the filter will not pass. We do not need to force failure.

2024-04-18 03:00 UTC, Quazia requested changes
Could you add some additional test coverage and make sure that the variables and filter are setup in a way that will be more compatible with adding more trading pairs and collateral contracts in the future?

2024-04-19 13:13 UTC, rontero83 commented on packages/gains/src/Gains.ts
> +}
change to throw pushing. is it ok?

2024-04-19 13:13 UTC, rontero83 commented on packages/gains/src/test-transactions.ts
> +]
add WBTC test transaction

2024-04-19 13:14 UTC, rontero83 commented on packages/gains/src/constants.ts
> +  '0x2c7e82641f03fa077f88833213210a86027f15dc'
renamed

2024-05-03 09:23 UTC, rontero83 commented
> Could you add some additional test coverage and make sure that the variables and filter are setup in a way that will be more compatible with adding more trading pairs and collateral contracts in the future?

Hi, @Quazia, @mmackz 
Have we any issues regarding to gain options pull request or not?

2024-06-21 17:06 UTC, closed without merging